export const UPDATE_RATING_REQUEST='UPDATE_RATING_REQUEST';
export const UPDATE_RATING_SUCCESS='UPDATE_RATING_SUCCESS';
export const UPDATE_RATING_FAIL='UPDATE_RATING_FAIL';

export const GET_COMMENT_REQUEST='GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS='GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAIL='GET_COMMENT_FAIL';