export const GET_PROMO_CODE_REQUEST = 'GET_PROMO_CODE_REQUEST';
export const GET_PROMO_CODE_SUCCESS = 'GET_PROMO_CODE_SUCCESS';
export const GET_PROMO_CODE_FAIL = 'GET_PROMO_CODE_FAIL';

export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_FAIL = 'GET_BANNER_FAIL';